### ISSUE TITLE
Pools suffering from erratum 2094 with asynchronous destroy fail to import with unhelpful error message

### ISSUE THREAD

**Issue by ryao** [zfsonlinux/zfs#2371]
fling in IRC had issues importing his pool. 

```
recovery ~ # zpool import backup
cannot import 'backup': pool may be in use from other system, it was last accessed by backup (hostid: 0x20d0a00) on Tue Jun  3 15:15:58 2014
use '-f' to import anyway
recovery ~ # zpool import -f backup
cannot import 'backup': I/O error
        Destroy and re-create the pool from
        a backup source.
```

Trying to run zdb segfaulted until going back to an older transaction group:

```
recovery ~ # zdb -d -p /dev -U /tmp -e backup
Segmentation fault
recovery ~ # zdb -t 1829763 -d -p /dev -U /tmp -e backup
Segmentation fault
recovery ~ # zdb -t 1829762 -d -p /dev -U /tmp -e backup
Dataset mos [META], ID 0, cr_txg 4, 1.64G, 3209 objects
<snip>
```

Examination with gdb showed that ZPOOL_ERRATA_ZOL_2094_ASYNC_DESTROY is being set. This is the callstack at that time:

```
#0  dsl_scan_init (dp=dp@entry=0x55555598b020, txg=1829764) at ../../module/zfs/dsl_scan.c:185
#1  0x00007ffff76a15ad in dsl_pool_open (dp=0x55555598b020) at ../../module/zfs/dsl_pool.c:274
#2  0x00007ffff76c8ac0 in spa_load_impl (ereport=<synthetic pointer>, mosconfig=B_TRUE, type=SPA_IMPORT_EXISTING, state=SPA_LOAD_IMPORT, config=<optimized out>, pool_guid=93824994520720, spa=0x555555776720) at ../../module/zfs/spa.c:2405
#3  spa_load (spa=spa@entry=0x555555776720, state=state@entry=SPA_LOAD_IMPORT, type=type@entry=SPA_IMPORT_EXISTING, mosconfig=mosconfig@entry=B_TRUE) at ../../module/zfs/spa.c:2094
#4  0x00007ffff76c9d67 in spa_load_best (spa=spa@entry=0x555555776720, state=SPA_LOAD_IMPORT, mosconfig=mosconfig@entry=1, max_request=<optimized out>, rewind_flags=2) at ../../module/zfs/spa.c:2791
#5  0x00007ffff76ca783 in spa_import (pool=pool@entry=0x5555557764b0 "backup", config=0x5555557764b8, props=0x0, props@entry=0x5555557764b8, flags=flags@entry=4) at ../../module/zfs/spa.c:3928
#6  0x000055555556163e in main (argc=1, argv=<optimized out>) at ../../cmd/zdb/zdb.c:3343
```

This is the callstack at the segmentation fault:

```
#0  0x00007ffff76cf9ef in spa_history_log_internal (spa=spa@entry=0x555555776720, operation=operation@entry=0x7ffff77125dc "import", tx=tx@entry=0x0, fmt=fmt@entry=0x7ffff7729d80 "pool version %llu; software version %llu/%d; uts %s %s %s %s")
    at ../../module/zfs/spa_history.c:488
#1  0x00007ffff76d002a in spa_history_log_version (spa=spa@entry=0x555555776720, operation=operation@entry=0x7ffff77125dc "import") at ../../module/zfs/spa_history.c:549
#2  0x00007ffff76ca736 in spa_import (pool=pool@entry=0x5555557764b0 "backup", config=0x5555557764b8, props=0x0, props@entry=0x5555557764b8, flags=flags@entry=1) at ../../module/zfs/spa.c:3904
#3  0x000055555556165c in main (argc=1, argv=<optimized out>) at ../../cmd/zdb/zdb.c:3345
```

Since the load failed, the dsl has been deallocated and set to NULL. This causes `spa_get_dsl(spa)->dp_mos_dir` to become `((dsl_pool_t *)NULL)->dp_mos_dir`, which is a NULL pointer dereference.

I plan to fix this so that we do not segfault and produce a helpful error message. However, I am jotting down what I know so far in an issue report for future reference.

**Comment by behlendorf** [comment]
This patch was merged as:

a5778ea zdb: Introduce -V for verbatim import
