### ISSUE TITLE
ztest: ztest_zap_parallel

### ISSUE THREAD

**Issue by behlendorf** [zfsonlinux/zfs#5271]
The `ztest_zap_parallel` test hit a checksum failure, ECKSUM (52), while setting up.  It's possible this was due to it using a zap object from a previous run and the issue could be avoid by setting the `remove` flag to B_TRUE in `ztest_object_init`.

http://build.zfsonlinux.org/builders/Amazon%202015.09%20x86_64%20Release%20%28TEST%29/builds/69/steps/shell_5/logs/stdio

```
#0  0x00007f81314435f7 in raise () from /lib64/libc.so.6
#1  0x00007f8131444ce8 in abort () from /lib64/libc.so.6
#2  0x000000000040891d in libspl_assert (buf=buf@entry=0x7f811b492c50 "zap_count(os, object, &count) == 0 (0x34 == 0x0)", file=file@entry=0x414c24 "ztest.c", func=func@entry=0x4185d0 <__FUNCTION__.18891> "ztest_zap_parallel", line=line@entry=4697) at ../../lib/libspl/include/assert.h:40
#3  0x0000000000412056 in ztest_zap_parallel (zd=<optimized out>, id=<optimized out>) at ztest.c:4697
#4  0x000000000040cbf3 in ztest_execute (id=11, zi=<optimized out>, test=<optimized out>) at ztest.c:5994
#5  ztest_thread (arg=0xb) at ztest.c:6041
#6  0x00007f8132bd8ccc in zk_thread_helper (arg=0x2d10840) at kernel.c:140
#7  0x00007f81317d7dc5 in start_thread () from /lib64/libpthread.so.0
#8  0x00007f8131504c9d in clone () from /lib64/libc.so.6
```

**Comment by behlendorf** [comment]
Closing, no longer observed in master.
