### ISSUE TITLE
ztest: dump_dir failure

### ISSUE THREAD

**Issue by behlendorf** [zfsonlinux/zfs#5274]
Observed while running zloop.sh.

http://build.zfsonlinux.org/builders/CentOS%207.1%20x86_64%20%28TEST%29/builds/3198/steps/shell_5/logs/stdio

```
Core was generated by `zdb -bccsv -d -U /mnt/zpool.cache ztest'.
Program terminated with signal 6, Aborted.
#0  0x00007f994f6e65f7 in raise () from /lib64/libc.so.6
*
* Backtrace 
*
#0  0x00007f994f6e65f7 in raise () from /lib64/libc.so.6
#1  0x00007f994f6e7ce8 in abort () from /lib64/libc.so.6
#2  0x0000000000406e1e in libspl_assert (buf=buf@entry=0x7ffe3e9964c0 "object_count == usedobjs (0x0 == 0x5)", func=func@entry=0x412890 <__FUNCTION__.18380> "dump_dir", line=line@entry=2094, file=0x4114c2 "zdb.c") at ../../lib/libspl/include/assert.h:40
#3  0x000000000040d4b9 in dump_dir (os=<optimized out>) at zdb.c:2094
#4  0x000000000040d9d8 in dump_one_dir (dsname=dsname@entry=0x1e49a10 "ztest/temp_22", arg=arg@entry=0x0) at zdb.c:2315
#5  0x00007f9950cb48be in dmu_objset_find_impl (spa=spa@entry=0x1ab13d0, name=name@entry=0x1e49a10 "ztest/temp_22", func=func@entry=0x40d950 <dump_one_dir>, arg=arg@entry=0x0, flags=flags@entry=3) at ../../module/zfs/dmu_objset.c:2246
#6  0x00007f9950cb49cd in dmu_objset_find_impl (spa=0x1ab13d0, name=name@entry=0x1ab13d0 "ztest", func=func@entry=0x40d950 <dump_one_dir>, arg=arg@entry=0x0, flags=flags@entry=3) at ../../module/zfs/dmu_objset.c:2189
#7  0x00007f9950cb9e32 in dmu_objset_find (name=0x1ab13d0 "ztest", func=func@entry=0x40d950 <dump_one_dir>, arg=arg@entry=0x0, flags=flags@entry=3) at ../../module/zfs/dmu_objset.c:2262
#8  0x000000000040e0fb in dump_zpool (spa=0x1ab13d0) at zdb.c:3142
#9  0x0000000000405a78 in main (argc=<optimized out>, argv=<optimized out>) at zdb.c:3897
```

**Comment by behlendorf** [comment]
Closing, no longer observed in master.
