### ISSUE TITLE
arc_summary.py crashes with -d option when called with Python 3

### ISSUE THREAD

**Issue by scotws** [zfsonlinux/zfs#6849]
### System information

Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       |  Ubuntu
Distribution Version    |  16.04 LTS
Linux Kernel                 |  4.10.0-38-generic
Architecture                 |  amd64
ZFS Version                  |  0.6.5.9-2
SPL Version                  |  0.6.5.9-1

### Describe the problem you're observing

arc_summary.py crashes when called with the option -d with Python 3. The problem does no occur with Python 2.

### Describe how to reproduce the problem

Run `python3 arc_summary.py -d`

### Include any warning/errors/backtraces from the system logs

```
Traceback (most recent call last):
  File "/usr/sbin/arc_summary.py", line 1148, in <module>
    main()
  File "/usr/sbin/arc_summary.py", line 1144, in main
    page(Kstat)
  File "/usr/sbin/arc_summary.py", line 1035, in _tunable_summary
    description_list = p.communicate()[0].strip().split('\0')
TypeError: a bytes-like object is required, not 'str'
```
### Tentative Diagnosis

Python 3 changed the way encoding is handled with files (see https://docs.python.org/3.0/whatsnew/3.0.html#text-vs-data-instead-of-unicode-vs-8-bit). It is probable that the pipe called here now returns the wrong sort of data.

**Comment by scotws** [comment]
After a bit of testing: Python2 returns a string as the first element of the tuple produced by `p.communicate()` here, but Python3 returns bytes. Will take a look at fixes and figure out a PR to fix this.
