### ISSUE TITLE
ztest: metaslab_group_passivate() deadlock

### ISSUE THREAD

**Issue by behlendorf** [zfsonlinux/zfs#7160]
### System information

Type                                | Version/Name
  ---                                  |     --- 
Distribution Name       | any
Distribution Version    |  any
Linux Kernel                 | any
Architecture                 | any
ZFS Version                  | zfs-0.7.0-310-gc03f04708c
SPL Version                  | spl-0.7.0-26-g48ef8ba07

### Describe the problem you're observing

Deadlock while running `zloop.sh` triggering the deadman.  The fix for this issue is included in #6900 which adds `zfs device evacuation/removal` functionality.

https://github.com/openzfs/openzfs/blob/master/usr/src/uts/common/fs/zfs/metaslab.c#L685-L700

```
Thread 476 (Thread 0x7f59d7dbe700 (LWP 32116)):
#0  0x00007f59e193951c in pthread_cond_wait@@GLIBC_2.3.2 ()
#1  0x00007f59e2b9d4a5 in cv_wait (cv=cv@entry=0x55accf3a3288,
#2  0x00007f59e2c20be3 in spa_config_enter (spa=spa@entry=0x55accf3a1be0,
#3  0x00007f59e2cb31da in zio_vdev_io_start (zio=0x7f5994049a80) at
#4  0x00007f59e2cb13cb in __zio_execute (zio=0x7f5994049a80) at
#5  zio_nowait (zio=0x7f5994049a80) at ../../module/zfs/zio.c:2012
#6  0x00007f59e2bb08ba in arc_read (pio=pio@entry=0x7f59940494c0,
#7  0x00007f59e2bb9d47 in dbuf_prefetch (dn=0x55accf539010,
#8  0x00007f59e2bc0a19 in dmu_prefetch (os=<optimized out>, object=<optimized
#9  0x00007f59e2c25fba in space_map_load (sm=0x55accf3faf50,
#10 0x00007f59e2c06454 in metaslab_load (msp=<optimized out>) at
#11 0x00007f59e2c06558 in metaslab_preload (arg=<optimized out>) at
#12 0x00007f59e2b9eed7 in taskq_thread (arg=0x55accf477e70) at taskq.c:233
#13 0x00007f59e1933574 in start_thread () from /lib64/libpthread.so.0
#14 0x00007f59e166745f in clone () from /lib64/libc.so.6

Thread 5 (Thread 0x7f59e450d8c0 (LWP 31219)):
#0  0x00007f59e193951c in pthread_cond_wait@@GLIBC_2.3.2 () from
#1  0x00007f59e2b9d4a5 in cv_wait (cv=cv@entry=0x55accf477f38,
#2  0x00007f59e2b9f29b in taskq_wait (tq=0x55accf477e70) at taskq.c:193
#3  0x00007f59e2c05a21 in metaslab_group_passivate (mg=<optimized out>) at
#4  0x00007f59e2c290b8 in vdev_metaslab_fini (vd=0x55accf3e2bf0) at
#5  0x00007f59e2c1489c in spa_unload (spa=<optimized out>) at
#6  0x00007f59e2c1607f in spa_evict_all () at ../../module/zfs/spa.c:7107
#7  0x00007f59e2c234b2 in spa_fini () at ../../module/zfs/spa_misc.c:1948
#8  0x00007f59e2b9ea62 in kernel_fini () at kernel.c:1037
#9  0x000055accd882f00 in ztest_run (zs=0x7f59e45264a0) at ztest.c:6671
#10 main (argc=<optimized out>, argv=<optimized out>) at ztest.c:7185
```

### Describe how to reproduce the problem

Reproducible by the buildbot and locally given enough run time.

### Include any warning/errors/backtraces from the system logs

http://build.zfsonlinux.org/builders/Fedora%20Rawhide%20x86_64%20%28TEST%29/builds/51

**Comment by behlendorf** [comment]
Closing.  This was resolved as part of #6900.
