### ISSUE TITLE
ztest: spa_vdev_removal_destroy() busy mutex

### ISSUE THREAD

**Issue by behlendorf** [zfsonlinux/zfs#9357]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	| Amazon Linux
Distribution Version	| 2
Linux Kernel	| 4.14.121-109.96.amzn2
Architecture	| x86_64
ZFS Version	| zfs-0.8.0-285-gd359e99
SPL Version	| 

### Describe the problem you're observing

Observed while running `ztest` in the CI.  It appears the `spa_vdev_removal_destroy()` function attempting to destroy a mutex while it was still held (EBUSY).

```
pthread_mutex_destroy(&mp->m_lock) == 0 (0x10 == 0)
ASSERT at kernel.c:201:mutex_destroy()/usr/sbin/ztest[0x40962e]
```

```
*
* Backtrace 
*
#0  0x00007fde87179760 in raise () from /lib64/libc.so.6
#1  0x00007fde8717ad41 in abort () from /lib64/libc.so.6
#2  0x00007fde88735e1b in libspl_assertf (file=0x7fde888c3200 "kernel.c", func=func@entry=0x7fde888c3808 <__FUNCTION__.11921> "mutex_destroy", line=line@entry=201, format=format@entry=0x7fde888c3237 "%s == 0 (0x%llx == 0)", file=0x7fde888c3200 "kernel.c") at ../../lib/libspl/include/assert.h:55
#3  0x00007fde8873873d in mutex_destroy (mp=mp@entry=0x7fde4c15a708) at kernel.c:201
#4  0x00007fde88848f8f in spa_vdev_removal_destroy (svr=0x7fde4c15a6d0) at ../../module/zfs/vdev_removal.c:222
#5  0x00007fde88849b0a in spa_finish_removal (tx=0x7fde4c312d60, state=DSS_FINISHED, spa=0x2373270) at ../../module/zfs/vdev_removal.c:695
#6  vdev_remove_complete_sync (arg=<optimized out>, tx=0x7fde4c312d60) at ../../module/zfs/vdev_removal.c:1106
#7  0x00007fde8879ee9c in dsl_sync_task_sync (dst=0x7fde2c016ab0, tx=0x7fde4c312d60) at ../../module/zfs/dsl_synctask.c:234
#8  0x00007fde88792bfb in dsl_pool_sync (dp=dp@entry=0x2404410, txg=txg@entry=352) at ../../module/zfs/dsl_pool.c:782
#9  0x00007fde887ba1fb in spa_sync_iterate_to_convergence (tx=0x7fde4c179390, spa=0x2373270) at ../../module/zfs/spa.c:8199
#10 spa_sync (spa=spa@entry=0x2373270, txg=txg@entry=352) at ../../module/zfs/spa.c:8408
#11 0x00007fde887ce8ec in txg_sync_thread (arg=0x2404410) at ../../module/zfs/txg.c:579
#12 0x00007fde8750254b in start_thread () from /lib64/libpthread.so.0
#13 0x00007fde8723a2ff in clone () from /lib64/libc.so.6
```

### Describe how to reproduce the problem

Run `zloop.sh`.

### Include any warning/errors/backtraces from the system logs

This have been observed several times in the CI, though I'm unsure if anyone's hit it locally when running `ztest`.  Logs:

http://build.zfsonlinux.org/builders/Amazon%202%20x86_64%20Release%20(TEST)/builds/5064
http://build.zfsonlinux.org/builders/Amazon%202%20x86_64%20Release%20(TEST)/builds/6713/
http://build.zfsonlinux.org/builders/CentOS%207%20x86_64%20(TEST)/builds/7906

**Comment by behlendorf** [comment]
This issue was resolved.
